### ISSUE TITLE
Favicon.png is still default in v0.3 beta

### ISSUE THREAD

**Issue by acuaroo** [SilentsReplacement/Octagon#10]
# Currently, Octagon still uses the default icon. 

Although I was suggesting in my PR for this to be added, you said it was included.

![image](https://user-images.githubusercontent.com/67112172/129075509-653b61d8-9819-4f1b-b1ee-a888c37cfd3e.png)

This should be a easy fix, the favicon.png Is located in `site/assets/images`, and can be replaced with a new icon.

**Comment by SilentsReplacement** [comment]
Octagon doesn’t need a banner, but a logo. I’ll make sure to add it in the  next version if you can send in just the logo slightly modified to look better.
