### ISSUE TITLE
Teleporting a player causes them to be flagged

### ISSUE THREAD

**Issue by SlipperySpelunky** [SilentsReplacement/Octagon#16]
I've noticed that teleporting a player, even if it's done on the server, can cause them to be flagged. In my case, there isn't a specific factor to consider in the teleportation length.

I'd assume this issue has to do with the player having network ownership of their client, therefore, causing movement replication, but if there is any way you can solve this issue, I'd appreciate it.

**Comment by SilentsReplacement** [comment]
Player having network ownership will have their character physics calculated locally and then replicated to the server.

However, Octagon will respect server sided changes.

Make sure that you are changing the CFrame of the player, not their position. Octagon will not detect positional changes on the server, only CFrame for unrelated reasons on how changing the position actually changes the position internally.
