### ISSUE TITLE
Whitelist is incorrectly named as "Blacklist"

### ISSUE THREAD

**Issue by ccuser44** [SilentsReplacement/Octagon#3]
The incorrect naming Whitelist as "Blacklist" really bothers me.

Definition of whitelist & Blacklist:
`
A whitelist (or, less commonly, a passlist or allowlist) is a mechanism which explicitly allows some identified entities to access a particular privilege, service, mobility, or recognition i.e. it is a list of things allowed when everything is denied by default. It is the opposite of a blacklist which is list of things denied when everything is allowed by default. 
`

So infact the "Blacklist" is a **Whitelist**

**Comment by SilentsReplacement** [comment]
Black list means "denied" and not allowed, so "BlacklistPlayerFromBeingMonitored" means "Deny player from being monitored". It is correctly spelled.

**Comment by ccuser44** [comment]
I disagree.
You don't "allow a player to be monitored" you "allow them **not to be** monitored".
Hence why whitelist is the correct naming.

**Comment by SilentsReplacement** [comment]
Fair enough, will fix this.
