### ISSUE TITLE
False detection

### ISSUE THREAD

**Issue by ccuser44** [SilentsReplacement/Octagon#7]
When a humanoid is running or jumping and their walkspeed and/or jumppower gets reduced, the anti cheat will false detect them.

This is because the velocity doesn't decelerate immediately after you decrease walksppeed / jumppower. This can be for example observed in the starter place, when you use the speedcoil and run, and then deselect the speedcoil the anti-cheat will false flag.

**Comment by SilentsReplacement** [comment]
Thanks for the report, a fix will arrive in the next update.

**Comment by SilentsReplacement** [comment]
Update on this: This has been completely fixed and the new solution to this is extremely reliable as well. Will be publishing this asap.
